"use client";

import { useState } from "react";

type Kind = "landing" | "dashboard" | "admin" | "mobile" | "ai";
const labels: Record<Kind, string[]> = { landing: ["Global Header", "Hero", "Trust / Proof", "Feature Overview", "Service Cards", "How It Works", "Call to Action", "Footer"], dashboard: ["App Header", "Side Navigation", "Page Header", "Summary Metrics", "Chart Area", "Status Overview", "Recent Activity", "Quick Actions"], admin: ["Admin Header", "Side Navigation", "Search and Filter", "Data Table", "Bulk Action", "Detail Drawer", "Create / Edit", "Delete Confirmation"], mobile: ["Safe Area", "Top App Bar", "Primary Content", "Sticky Action", "Bottom Navigation"], ai: ["Workspace Header", "Context Panel", "AI Result", "Prompt Composer", "Tool Status", "Source / Review"] };

function Header({ title, description }: { title: string; description: string }) { return <header className="template-header"><div><span className="template-eyebrow">TEMPLATE v1.0 · SAMPLE</span><h1>{title}</h1><p>{description}</p></div><div className="template-toolbar"><button className="active">Preview</button><button>Anatomy</button></div></header>; }
function Anatomy({ kind }: { kind: Kind }) { return <div className="template-anatomy">{labels[kind].map((item, index) => <div key={item}><b>{String(index + 1).padStart(2, "0")}</b><span>{item}</span></div>)}</div>; }
function Metric({ label, value, tone = "" }: { label: string; value: string; tone?: string }) { return <div className={`template-metric ${tone}`}><small>{label}</small><strong>{value}</strong><span>Sample data</span></div>; }

function Landing() { return <div className="template-landing"><div className="template-nav"><strong>NexDataForge</strong><span>Services</span><span>How it works</span><button className="template-primary">Get started</button></div><div className="template-hero"><div><span className="template-eyebrow">DATA WORKFLOWS, SIMPLIFIED</span><h2>Turn complex requests into clear next steps.</h2><p>A practical workspace for projects, analysis, and decisions across your service portfolio.</p><div className="template-actions"><button className="template-primary">Create a request</button><button className="template-secondary">Explore services</button></div></div><div className="template-preview-card"><span>Sample preview</span><strong>Project Atlas</strong><p>3 datasets connected</p><div className="template-bar"><i /></div></div></div><div className="template-features">{["One clear workspace", "Guided AI assistance", "Reviewable results"].map((item) => <div key={item}><b>+</b><strong>{item}</strong><span>Designed for focused, repeatable work.</span></div>)}</div></div>; }
function Dashboard() { return <div className="template-dashboard"><aside className="template-side"><strong>NexDataForge</strong><a className="selected">Overview</a><a>Projects</a><a>Requests</a><a>Settings</a></aside><div className="template-main"><div className="template-page-title"><div><small>HOME / OVERVIEW</small><h2>Project overview</h2><p>Monitor activity across your workspace.</p></div><button className="template-primary">New project</button></div><div className="template-metrics"><Metric label="All projects" value="24" /><Metric label="In progress" value="08" tone="good" /><Metric label="Needs review" value="03" tone="warn" /><Metric label="Errors" value="01" tone="bad" /></div><div className="template-dashboard-grid"><div className="template-chart"><strong>Weekly progress</strong><div className="template-chart-lines"><i /><i /><i /><i /><i /></div><small>Sample visualization · Last 7 days</small></div><div className="template-activity"><strong>Recent activity</strong><p>Project Atlas updated <small>12 min ago</small></p><p>AI review completed <small>1 hr ago</small></p><p>New request created <small>Yesterday</small></p></div></div></div></div>; }
function Admin() { return <div className="template-admin"><aside className="template-side"><strong>Admin Console</strong><a className="selected">Metadata</a><a>Users</a><a>Audit history</a></aside><div className="template-main"><div className="template-page-title"><div><small>ADMIN / METADATA</small><h2>Metadata entries</h2><p>Manage structured records and status.</p></div><button className="template-primary">Add entry</button></div><div className="template-filter"><input aria-label="Search metadata" placeholder="Search metadata" /><button>All statuses</button><button>Reset</button></div><div className="template-table"><div className="template-table-row heading"><span>Code</span><span>Name</span><span>Status</span><span>Updated</span></div>{["SW007-001", "SW007-002", "SW007-003"].map((item, index) => <div className="template-table-row" key={item}><span>{item}</span><strong>{["Project state", "Service type", "Review status"][index]}</strong><span className={index === 1 ? "template-warn" : "template-good"}>{index === 1 ? "Review" : "Active"}</span><span>Today ·•••</span></div>)}</div></div></div>; }
function Mobile() { return <div className="template-device"><div className="template-device-top"><span>9:41</span><b>●●●</b></div><div className="template-mobile-content"><small>GOOD MORNING</small><h3>What would you like to do?</h3><div className="template-mobile-card"><span>Primary task</span><strong>Start a new request</strong><button className="template-primary">Begin</button></div><strong>Recent items</strong><div className="template-mobile-row">Project Atlas <small>Ready</small></div><div className="template-mobile-row">Store operations <small>Review</small></div></div><div className="template-bottom-nav"><span className="selected">⌂<small>Home</small></span><span>⌕<small>Search</small></span><span>＋<small>Create</small></span><span>◎<small>My</small></span></div></div>; }
function AIWorkspace() { return <div className="template-ai-workspace"><aside><strong>Context</strong><div className="template-context">Project Atlas<span>3 datasets</span></div><div className="template-context">Goal<span>Prepare review</span></div></aside><main><div className="template-ai-result"><span className="template-eyebrow">AI RESULT · SAMPLE</span><h3>Project review summary</h3><p>The project is ready for review. One source needs confirmation before the next action.</p><button className="template-secondary">Request revision</button></div><div className="template-prompt"><label htmlFor="workspace-prompt">Ask a follow-up</label><div><input id="workspace-prompt" placeholder="Ask about this result..." /><button className="template-primary">Send</button></div></div></main><aside className="template-review"><strong>Review panel</strong><p>Confidence <b>Medium</b></p><p>Sources <b>2 available</b></p><button className="template-primary">Review result</button></aside></div>; }

export function TemplateStudio({ kind, title, description }: { kind: Kind; title: string; description: string }) { const [mode, setMode] = useState<"preview" | "anatomy">("preview"); const [device, setDevice] = useState("desktop"); const body = kind === "landing" ? <Landing /> : kind === "dashboard" ? <Dashboard /> : kind === "admin" ? <Admin /> : kind === "mobile" ? <Mobile /> : <AIWorkspace />; return <main className="template-studio"><div className="template-shell"><a className="template-back" href="/studio/templates">← Templates</a><Header title={title} description={description} /><div className="template-controls"><div><button className={mode === "preview" ? "active" : ""} onClick={() => setMode("preview")}>Preview</button><button className={mode === "anatomy" ? "active" : ""} onClick={() => setMode("anatomy")}>Anatomy</button></div><div><button className={device === "desktop" ? "active" : ""} onClick={() => setDevice("desktop")}>Desktop</button><button className={device === "tablet" ? "active" : ""} onClick={() => setDevice("tablet")}>Tablet</button><button className={device === "mobile" ? "active" : ""} onClick={() => setDevice("mobile")}>Mobile</button></div></div><div className={`template-canvas ${device} ${mode}`}>{mode === "preview" ? body : <Anatomy kind={kind} />}</div><div className="template-notes"><div><strong>Responsive notes</strong><span>Desktop uses the full shell; tablet reduces columns; mobile uses a single flow with compact actions.</span></div><div><strong>Sample data</strong><span>All content is preview data. No API, database, auth, file, chart, or AI service is connected.</span></div></div></div></main>; }
