import "server-only";
import { query, transaction } from "./sw006-db";
export type Word={word_seq:number;word_kr_nm:string;word_eng_nm:string;word_abbr_nm:string;word_desc:string|null;use_yn:"Y"|"N";upd_dt:string|null};
export type Domain={domain_seq:number;domain_nm:string;domain_eng_nm:string|null;domain_phys_nm:string;data_type_nm:string;data_len:number|null;data_precision:number|null;data_scale:number|null;nullable_yn:"Y"|"N";default_val:string|null;domain_format_desc:string|null;domain_desc:string|null;use_yn:"Y"|"N";upd_dt:string|null};
const like=(s:string)=>`%${s}%`;
export async function listWords(q="",use="all"){return(await query<Word>(`select word_seq,word_kr_nm,word_eng_nm,word_abbr_nm,word_desc,use_yn,upd_dt from meta_word where ($1='' or word_kr_nm ilike $2 or word_eng_nm ilike $2 or word_abbr_nm ilike $2) and ($3='all' or use_yn=$3) order by word_seq desc`,[q,like(q),use])).rows;}
export async function listDomains(q="",use="all",type="all"){return(await query<Domain>(`select domain_seq,domain_nm,domain_eng_nm,domain_phys_nm,data_type_nm,data_len,data_precision,data_scale,nullable_yn,default_val,domain_format_desc,domain_desc,use_yn,upd_dt from meta_domain where ($1='' or domain_nm ilike $2 or domain_eng_nm ilike $2 or domain_phys_nm ilike $2) and ($3='all' or use_yn=$3) and ($4='all' or data_type_nm=$4) order by domain_seq desc`,[q,like(q),use,type])).rows;}
export async function history(){return(await query(`select change_his_seq,change_tgt_cd,change_type_cd,word_seq,domain_seq,before_val,after_val,change_reason,change_user_nm,change_dt from meta_change_his order by change_dt desc limit 50`)).rows;}
export async function stats(){return(await query(`select (select count(*) from meta_word)::int word_total,(select count(*) from meta_word where use_yn='Y')::int word_active,(select count(*) from meta_domain)::int domain_total,(select count(*) from meta_domain where use_yn='Y')::int domain_active,(select count(*) from meta_change_his)::int history_total`)).rows[0];}
function validateDomain(d:Record<string,unknown>){const t=String(d.data_type_nm??"").toUpperCase();if(!d.domain_nm||!d.domain_phys_nm||!t)throw new Error("도메인명, 물리명, 데이터 타입은 필수입니다.");if(["VARCHAR","CHAR"].includes(t)&&(!Number.isInteger(d.data_len)||Number(d.data_len)<=0))throw new Error("문자형 데이터 타입은 길이를 입력하세요.");if(["NUMERIC","DECIMAL"].includes(t)&&(!Number.isInteger(d.data_precision)||Number(d.data_precision)<=0))throw new Error("수치형 데이터 타입은 precision을 입력하세요.");if(d.data_scale!==null&&d.data_scale!==undefined&&Number(d.data_scale)>Number(d.data_precision))throw new Error("scale은 precision보다 클 수 없습니다.");}
export async function saveWord(id:number|undefined,d:Record<string,unknown>){if(!d.word_kr_nm||!d.word_eng_nm||!d.word_abbr_nm)throw new Error("한글명, 영문명, 약어는 필수입니다.");return transaction(async c=>{let row:any,before:any=null,type="INSERT";if(id){const old=await c.query("select * from meta_word where word_seq=$1",[id]);if(!old.rowCount)throw new Error("존재하지 않는 표준 단어입니다.");before=old.rows[0];row=(await c.query("update meta_word set word_kr_nm=$1,word_eng_nm=$2,word_abbr_nm=$3,word_desc=$4,use_yn=$5,upd_user_nm=current_user,upd_dt=current_timestamp where word_seq=$6 returning *",[d.word_kr_nm,d.word_eng_nm,d.word_abbr_nm,d.word_desc??null,d.use_yn??"Y",id])).rows[0];type=before.use_yn!==row.use_yn?(row.use_yn==="Y"?"ENABLE":"DISABLE"):"UPDATE";}else row=(await c.query("insert into meta_word(word_kr_nm,word_eng_nm,word_abbr_nm,word_desc,use_yn) values($1,$2,$3,$4,$5) returning *",[d.word_kr_nm,d.word_eng_nm,d.word_abbr_nm,d.word_desc??null,d.use_yn??"Y"])).rows[0];await c.query("insert into meta_change_his(change_tgt_cd,change_type_cd,word_seq,before_val,after_val,change_reason) values('WORD',$1,$2,$3,$4,$5)",[type,row.word_seq,before,row,d.change_reason??null]);return row;});}
export async function saveDomain(id:number|undefined,d:Record<string,unknown>){validateDomain(d);return transaction(async c=>{let row:any,before:any=null,type="INSERT";const vals=[d.domain_nm,d.domain_eng_nm??null,d.domain_phys_nm,String(d.data_type_nm).toUpperCase(),d.data_len??null,d.data_precision??null,d.data_scale??null,d.nullable_yn??"Y",d.default_val??null,d.domain_format_desc??null,d.domain_desc??null,d.use_yn??"Y"];if(id){const old=await c.query("select * from meta_domain where domain_seq=$1",[id]);if(!old.rowCount)throw new Error("존재하지 않는 표준 도메인입니다.");before=old.rows[0];row=(await c.query("update meta_domain set domain_nm=$1,domain_eng_nm=$2,domain_phys_nm=$3,data_type_nm=$4,data_len=$5,data_precision=$6,data_scale=$7,nullable_yn=$8,default_val=$9,domain_format_desc=$10,domain_desc=$11,use_yn=$12,upd_user_nm=current_user,upd_dt=current_timestamp where domain_seq=$13 returning *",[...vals,id])).rows[0];type=before.use_yn!==row.use_yn?(row.use_yn==="Y"?"ENABLE":"DISABLE"):"UPDATE";}else row=(await c.query("insert into meta_domain(domain_nm,domain_eng_nm,domain_phys_nm,data_type_nm,data_len,data_precision,data_scale,nullable_yn,default_val,domain_format_desc,domain_desc,use_yn) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning *",vals)).rows[0];await c.query("insert into meta_change_his(change_tgt_cd,change_type_cd,domain_seq,before_val,after_val,change_reason) values('DOMAIN',$1,$2,$3,$4,$5)",[type,row.domain_seq,before,row,d.change_reason??null]);return row;});}
export function apiError(e:unknown){const code=(e as {code?:string})?.code;const message=code==="23505"?"이미 존재하는 값입니다.":code?.startsWith("23")?"입력값이 데이터베이스 제약조건에 맞지 않습니다.":e instanceof Error?e.message:"처리 중 오류가 발생했습니다.";return Response.json({success:false,message},{status:400});}
