"use client";

import { useState } from "react";

const nav = [["Getting Started", "/studio/docs/getting-started"], ["Design Principles", "/studio/docs/design-principles"], ["Usage", "/studio/docs/usage"], ["Adoption", "/studio/docs/adoption"], ["Migration", "/studio/docs/migration"], ["Contributing", "/studio/docs/contributing"], ["Versioning", "/studio/docs/versioning"]];
export function DocsLayout({ title, eyebrow, summary, children }: { title: string; eyebrow: string; summary: string; children: React.ReactNode }) { return <main className="docs-page"><div className="docs-shell"><a className="docs-back" href="/studio/docs">← Documentation</a><header className="docs-header"><span>{eyebrow}</span><h1>{title}</h1><p>{summary}</p></header><div className="docs-layout"><nav className="docs-nav" aria-label="Documentation"><strong>Documentation</strong>{nav.map(([label, href]) => <a href={href} key={label}>{label}</a>)}</nav><article className="docs-content">{children}</article></div></div></main>; }
export function DocsSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="docs-section"><h2>{title}</h2>{children}</section>; }
export function GuidelineList({ items }: { items: string[] }) { return <ul className="docs-list">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
export function AdoptionLevels() { const levels = ["Level 0 · Unassessed", "Level 1 · Foundation Aligned", "Level 2 · Component Aligned", "Level 3 · Pattern Aligned", "Level 4 · Template Aligned", "Level 5 · Quality Gate Ready"]; return <div className="docs-levels">{levels.map((level, index) => <div key={level}><b>{index}</b><span>{level}</span><small>{index === 5 ? "Lint, TypeScript, build, responsive, accessibility, and route checks." : "Use this as an adoption description, not a project score."}</small></div>)}</div>; }
export function ReadinessChecklist() { const [checked, setChecked] = useState<string[]>([]); const items = ["Project purpose defined", "UI inventory complete", "Foundation scope agreed", "Template and pattern selected", "Responsive baseline defined", "Accessibility baseline defined", "Rollback plan defined", "Quality Gate reviewed"]; return <div className="docs-checklist">{items.map((item) => <label key={item}><input type="checkbox" checked={checked.includes(item)} onChange={() => setChecked(checked.includes(item) ? checked.filter((x) => x !== item) : [...checked, item])} />{item}</label>)}</div>; }
export function CodeExample() { return <pre className="docs-code"><code>{`.example-card {\n  background: var(--ndf-color-bg-surface);\n  color: var(--ndf-color-text-primary);\n  border-radius: var(--ndf-card-radius);\n  box-shadow: var(--ndf-card-shadow);\n}`}</code></pre>; }
