begin;

lock table menus in exclusive mode;
lock table pages in exclusive mode;

create temporary table menu_id_migration_map on commit drop as
select id as old_id,
       row_number() over (order by created_at nulls last, id)::bigint as new_id
from menus;

alter table menus alter column id drop default;

alter table menus alter column parent_id type text using parent_id::text;
alter table pages alter column menu_id type text using menu_id::text;
alter table menus alter column id type text using id::text;

update menus c set parent_id = m.new_id::text from menu_id_migration_map m where c.parent_id = m.old_id::text;
update pages c set menu_id = m.new_id::text from menu_id_migration_map m where c.menu_id = m.old_id::text;
update main_sections s set section_type = 'MENU_' || m.new_id::text from menu_id_migration_map m where s.section_type = 'MENU_' || m.old_id::text;
update menus c set id = m.new_id::text from menu_id_migration_map m where c.id = m.old_id::text;

alter table menus alter column id type bigint using id::bigint;
alter table menus alter column parent_id type bigint using parent_id::bigint;
alter table pages alter column menu_id type bigint using menu_id::bigint;

alter table menus alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('menus', 'id'), coalesce((select max(id) from menus), 1), (select count(*) > 0 from menus));

commit;
