-- SW_006 AI Website Factory - simple PostgreSQL schema
-- Scope: CREATE TABLE + PRIMARY KEY + COMMENT + GRANT

begin;

create extension if not exists pgcrypto;

create sequence profile_id_sequence start with 1 minvalue 1;
create sequence generation_job_id_sequence start with 1 minvalue 1;
create sequence board_id_sequence start with 1 minvalue 1 maxvalue 9999999;
create sequence page_id_sequence start with 1 minvalue 1;
create sequence main_section_id_sequence start with 1 minvalue 1;
create sequence generated_file_id_sequence start with 1 minvalue 1;

create or replace function next_profile_id()
returns varchar(22)
language sql
as $$
  select ('USR-' || nextval('profile_id_sequence')::text)::varchar(22);
$$;

create or replace function next_generation_job_id()
returns varchar(22)
language sql
as $$
  select ('GE-' || nextval('generation_job_id_sequence')::text)::varchar(22);
$$;

create or replace function next_board_id()
returns varchar(11)
language plpgsql
as $$
declare
  next_number bigint := nextval('board_id_sequence');
begin
  if next_number > 9999999 then raise exception '게시판 ID를 9999999개보다 많이 생성할 수 없습니다.'; end if;
  return 'BBS-' || next_number::text;
end;
$$;

create or replace function next_page_id()
returns varchar(22)
language sql
as $$
  select ('PG-' || nextval('page_id_sequence')::text)::varchar(22);
$$;

create or replace function next_main_section_id()
returns varchar(22)
language sql
as $$
  select ('MS-' || nextval('main_section_id_sequence')::text)::varchar(22);
$$;

create or replace function next_generated_file_id()
returns varchar(22)
language sql
as $$
  select ('GEF-' || nextval('generated_file_id_sequence')::text)::varchar(22);
$$;

create or replace function next_site_id()
returns bigint
language plpgsql
as $$
declare
  day_prefix bigint := to_char(current_date, 'YYYYMMDD')::bigint * 10000;
  next_number integer;
begin
  perform pg_advisory_xact_lock(hashtext('sites_daily_id_' || current_date::text));
  select coalesce(max((id - day_prefix)::integer), 0) + 1
    into next_number
    from sites
   where id between day_prefix and day_prefix + 9999;
  if next_number > 9999 then raise exception '하루에 사이트 ID를 9999개보다 많이 생성할 수 없습니다.'; end if;
  return day_prefix + next_number;
end;
$$;

create table profiles (
  id varchar(22) default next_profile_id(),
  auth_user_id uuid,
  login_id varchar(100),
  display_name varchar(100),
  email varchar(200),
  company_slug varchar(100),
  access_level varchar(30) default 'SITE_USER',
  password_hash text,
  phone varchar(50),
  avatar_url text,
  is_platform_admin boolean default false,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table sites (
  id bigint default next_site_id(),
  company_slug varchar(100),
  name varchar(200),
  industry varchar(100),
  manager_name varchar(100),
  memo text,
  status varchar(30) default 'DRAFT',
  output_path text,
  created_by varchar(22),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table templates (
  id uuid default gen_random_uuid(),
  code varchar(100),
  name varchar(200),
  description text,
  thumbnail_url text,
  config jsonb default '{}'::jsonb,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table site_templates (
  site_id bigint,
  template_id uuid,
  theme_config jsonb default '{}'::jsonb,
  selected_by varchar(22),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (site_id)
);

create table menus (
  id bigint generated by default as identity,
  site_id bigint,
  parent_id bigint,
  depth smallint default 1,
  name varchar(200),
  slug varchar(200),
  url_type varchar(30) default 'PAGE',
  external_url text,
  sort_order integer default 0,
  is_enabled boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table footers (
  site_id bigint,
  company_name varchar(200),
  representative_name varchar(100),
  business_number varchar(50),
  email varchar(200),
  phone varchar(50),
  address text,
  copyright_text text,
  site_by_text varchar(200),
  policy_links jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (site_id)
);

create table main_sections (
  id varchar(22) default next_main_section_id(),
  site_id bigint,
  section_type varchar(50),
  title varchar(300),
  subtitle varchar(500),
  body text,
  asset_id uuid,
  config jsonb default '{}'::jsonb,
  sort_order integer default 0,
  is_enabled boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table assets (
  id uuid default gen_random_uuid(),
  site_id bigint,
  bucket_name varchar(100),
  storage_path text,
  original_name varchar(500),
  mime_type varchar(200),
  size_bytes bigint,
  alt_text varchar(500),
  uploaded_by varchar(22),
  created_at timestamptz default now(),
  primary key (id)
);

create table pages (
  id varchar(22) default next_page_id(),
  site_id bigint,
  menu_id bigint,
  slug varchar(200),
  title varchar(300),
  content jsonb default '{}'::jsonb,
  seo_title varchar(300),
  seo_description text,
  status varchar(30) default 'DRAFT',
  published_at timestamptz,
  created_by varchar(22),
  updated_by varchar(22),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table boards (
  id varchar(11) default next_board_id(),
  site_id bigint,
  code varchar(100),
  name varchar(200),
  description text,
  allow_files boolean default true,
  is_enabled boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table board_posts (
  id bigint generated always as identity,
  site_id bigint,
  board_id varchar(11),
  title varchar(500),
  content text,
  status varchar(30) default 'DRAFT',
  is_notice boolean default false,
  view_count bigint default 0,
  author_id varchar(22),
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table board_files (
  id uuid default gen_random_uuid(),
  post_id bigint,
  asset_id uuid,
  sort_order integer default 0,
  created_at timestamptz default now(),
  primary key (id)
);

create table generation_jobs (
  id varchar(22) default next_generation_job_id(),
  site_id bigint,
  status varchar(30) default 'QUEUED',
  progress smallint default 0,
  current_step varchar(200),
  log jsonb default '[]'::jsonb,
  error_message text,
  requested_by varchar(22),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (id)
);

create table generated_files (
  id varchar(22) default next_generated_file_id(),
  site_id bigint,
  generation_job_id varchar(22),
  relative_path text,
  content_hash varchar(200),
  size_bytes bigint default 0,
  created_at timestamptz default now(),
  primary key (id)
);

-- -----------------------------------------------------------------------------
-- 테이블 및 컬럼 한글 설명
-- -----------------------------------------------------------------------------
comment on table profiles is '사용자 프로필 정보';
comment on column profiles.id is '프로필 고유 ID';
comment on column profiles.auth_user_id is 'Supabase Auth 사용자 ID';
comment on column profiles.login_id is '사용자 로그인 아이디';
comment on column profiles.display_name is '사용자 표시 이름';
comment on column profiles.email is '사용자 이메일';
comment on column profiles.company_slug is '사이트사용자 담당 업체 영문명';
comment on column profiles.access_level is '권한 구분: SUPER_ADMIN 또는 SITE_USER';
comment on column profiles.password_hash is 'salt가 포함된 단방향 비밀번호 해시';
comment on column profiles.phone is '사용자 전화번호';
comment on column profiles.avatar_url is '프로필 이미지 URL';
comment on column profiles.is_platform_admin is '플랫폼 관리자 여부';
comment on column profiles.is_active is '사용 여부';
comment on column profiles.created_at is '생성 일시';
comment on column profiles.updated_at is '수정 일시';

comment on table sites is '업체별 웹사이트 기본 정보';
comment on column sites.id is '사이트 고유 ID';
comment on column sites.company_slug is '업체 영문 식별자';
comment on column sites.name is '사이트명';
comment on column sites.industry is '업종';
comment on column sites.manager_name is '담당자명';
comment on column sites.memo is '관리자 메모';
comment on column sites.status is '사이트 제작 및 운영 상태';
comment on column sites.output_path is '생성 파일 출력 경로';
comment on column sites.created_by is '사이트 생성자 ID';
comment on column sites.created_at is '생성 일시';
comment on column sites.updated_at is '수정 일시';

comment on table templates is '웹사이트 디자인 템플릿 정보';
comment on column templates.id is '템플릿 고유 ID';
comment on column templates.code is '템플릿 코드';
comment on column templates.name is '템플릿명';
comment on column templates.description is '템플릿 설명';
comment on column templates.thumbnail_url is '템플릿 미리보기 이미지 URL';
comment on column templates.config is '템플릿 기본 설정 JSON';
comment on column templates.is_active is '사용 여부';
comment on column templates.created_at is '생성 일시';
comment on column templates.updated_at is '수정 일시';

comment on table site_templates is '사이트에 선택된 템플릿 정보';
comment on column site_templates.site_id is '사이트 ID';
comment on column site_templates.template_id is '템플릿 ID';
comment on column site_templates.theme_config is '사이트별 테마 설정 JSON';
comment on column site_templates.selected_by is '템플릿 선택 사용자 ID';
comment on column site_templates.created_at is '생성 일시';
comment on column site_templates.updated_at is '수정 일시';

comment on table menus is '사이트 대메뉴 및 소메뉴 정보';
comment on column menus.id is '메뉴 고유 ID';
comment on column menus.site_id is '사이트 ID';
comment on column menus.parent_id is '상위 메뉴 ID';
comment on column menus.depth is '메뉴 단계';
comment on column menus.name is '메뉴명';
comment on column menus.slug is '메뉴 URL 식별자';
comment on column menus.url_type is '메뉴 연결 유형';
comment on column menus.external_url is '외부 연결 URL';
comment on column menus.sort_order is '표시 순서';
comment on column menus.is_enabled is '메뉴 사용 여부';
comment on column menus.created_at is '생성 일시';
comment on column menus.updated_at is '수정 일시';

comment on table footers is '사이트 푸터 정보';
comment on column footers.site_id is '사이트 ID';
comment on column footers.company_name is '회사명';
comment on column footers.representative_name is '대표자명';
comment on column footers.business_number is '사업자등록번호';
comment on column footers.email is '대표 이메일';
comment on column footers.phone is '대표 전화번호';
comment on column footers.address is '회사 주소';
comment on column footers.copyright_text is '저작권 표시 문구';
comment on column footers.site_by_text is '사이트 제작사 표시 문구';
comment on column footers.policy_links is '약관 및 정책 링크 JSON';
comment on column footers.created_at is '생성 일시';
comment on column footers.updated_at is '수정 일시';

comment on table main_sections is '사이트 메인 화면 섹션 정보';
comment on column main_sections.id is '메인 섹션 고유 ID';
comment on column main_sections.site_id is '사이트 ID';
comment on column main_sections.section_type is '섹션 유형';
comment on column main_sections.title is '섹션 제목';
comment on column main_sections.subtitle is '섹션 부제목';
comment on column main_sections.body is '섹션 본문';
comment on column main_sections.asset_id is '대표 이미지 자산 ID';
comment on column main_sections.config is '섹션 추가 설정 JSON';
comment on column main_sections.sort_order is '표시 순서';
comment on column main_sections.is_enabled is '섹션 사용 여부';
comment on column main_sections.created_at is '생성 일시';
comment on column main_sections.updated_at is '수정 일시';

comment on table assets is '사이트 이미지 및 첨부파일 정보';
comment on column assets.id is '자산 고유 ID';
comment on column assets.site_id is '사이트 ID';
comment on column assets.bucket_name is 'Supabase Storage 버킷명';
comment on column assets.storage_path is 'Storage 저장 경로';
comment on column assets.original_name is '원본 파일명';
comment on column assets.mime_type is '파일 MIME 유형';
comment on column assets.size_bytes is '파일 크기 바이트';
comment on column assets.alt_text is '이미지 대체 문구';
comment on column assets.uploaded_by is '업로드 사용자 ID';
comment on column assets.created_at is '생성 일시';

comment on table pages is '사이트 일반 페이지 정보';
comment on column pages.id is '페이지 고유 ID';
comment on column pages.site_id is '사이트 ID';
comment on column pages.menu_id is '연결 메뉴 ID';
comment on column pages.slug is '페이지 URL 식별자';
comment on column pages.title is '페이지 제목';
comment on column pages.content is '페이지 콘텐츠 JSON';
comment on column pages.seo_title is '검색엔진 최적화 제목';
comment on column pages.seo_description is '검색엔진 최적화 설명';
comment on column pages.status is '페이지 게시 상태';
comment on column pages.published_at is '게시 일시';
comment on column pages.created_by is '생성 사용자 ID';
comment on column pages.updated_by is '최종 수정 사용자 ID';
comment on column pages.created_at is '생성 일시';
comment on column pages.updated_at is '수정 일시';

comment on table boards is '사이트 게시판 정보';
comment on column boards.id is '게시판 고유 ID';
comment on column boards.site_id is '사이트 ID';
comment on column boards.code is '게시판 코드';
comment on column boards.name is '게시판명';
comment on column boards.description is '게시판 설명';
comment on column boards.allow_files is '첨부파일 허용 여부';
comment on column boards.is_enabled is '게시판 사용 여부';
comment on column boards.created_at is '생성 일시';
comment on column boards.updated_at is '수정 일시';

comment on table board_posts is '게시판 게시글 정보';
comment on column board_posts.id is '게시글 고유 ID';
comment on column board_posts.site_id is '사이트 ID';
comment on column board_posts.board_id is '게시판 ID';
comment on column board_posts.title is '게시글 제목';
comment on column board_posts.content is '게시글 내용';
comment on column board_posts.status is '게시 상태';
comment on column board_posts.is_notice is '공지글 여부';
comment on column board_posts.view_count is '조회수';
comment on column board_posts.author_id is '작성자 ID';
comment on column board_posts.published_at is '게시 일시';
comment on column board_posts.created_at is '생성 일시';
comment on column board_posts.updated_at is '수정 일시';

comment on table board_files is '게시글 첨부파일 연결 정보';
comment on column board_files.id is '첨부파일 연결 고유 ID';
comment on column board_files.post_id is '게시글 ID';
comment on column board_files.asset_id is '파일 자산 ID';
comment on column board_files.sort_order is '첨부파일 표시 순서';
comment on column board_files.created_at is '생성 일시';

comment on table generation_jobs is '웹사이트 파일 생성 작업 정보';
comment on column generation_jobs.id is '생성 작업 고유 ID';
comment on column generation_jobs.site_id is '사이트 ID';
comment on column generation_jobs.status is '작업 상태';
comment on column generation_jobs.progress is '작업 진행률';
comment on column generation_jobs.current_step is '현재 작업 단계';
comment on column generation_jobs.log is '단계별 작업 로그 JSON';
comment on column generation_jobs.error_message is '오류 메시지';
comment on column generation_jobs.requested_by is '작업 요청 사용자 ID';
comment on column generation_jobs.started_at is '작업 시작 일시';
comment on column generation_jobs.completed_at is '작업 완료 일시';
comment on column generation_jobs.created_at is '생성 일시';
comment on column generation_jobs.updated_at is '수정 일시';

comment on table generated_files is '생성된 웹사이트 파일 정보';
comment on column generated_files.id is '생성 파일 고유 ID';
comment on column generated_files.site_id is '사이트 ID';
comment on column generated_files.generation_job_id is '파일 생성 작업 ID';
comment on column generated_files.relative_path is '생성 파일 상대 경로';
comment on column generated_files.content_hash is '파일 내용 해시';
comment on column generated_files.size_bytes is '파일 크기 바이트';
comment on column generated_files.created_at is '생성 일시';

-- Table grants
grant select, insert, update, delete on
  profiles,
  sites,
  templates,
  site_templates,
  menus,
  footers,
  main_sections,
  assets,
  pages,
  boards,
  board_posts,
  board_files,
  generation_jobs,
  generated_files
to authenticated, service_role;

-- Identity sequence grants
grant usage, select on sequence profile_id_sequence to authenticated, service_role;
grant usage, select on sequence generation_job_id_sequence to authenticated, service_role;
grant usage, select on sequence board_id_sequence to authenticated, service_role;
grant usage, select on sequence page_id_sequence to authenticated, service_role;
grant usage, select on sequence main_section_id_sequence to authenticated, service_role;
grant usage, select on sequence generated_file_id_sequence to authenticated, service_role;
grant usage, select on sequence board_posts_id_seq to authenticated, service_role;

commit;
