begin;

lock table boards in exclusive mode;
lock table menus in exclusive mode;
lock table board_posts in exclusive mode;

create temporary table board_id_migration_map on commit drop as
select id as old_id,
       row_number() over (order by created_at nulls last, id)::bigint as new_id
from boards;

alter table menus drop constraint if exists menus_board_id_fkey;
alter table boards alter column id drop default;

alter table menus alter column board_id type text using board_id::text;
alter table board_posts alter column board_id type text using board_id::text;
alter table boards alter column id type text using id::text;

update menus c set board_id = m.new_id::text from board_id_migration_map m where c.board_id = m.old_id::text;
update board_posts c set board_id = m.new_id::text from board_id_migration_map m where c.board_id = m.old_id::text;
update boards b set id = m.new_id::text from board_id_migration_map m where b.id = m.old_id::text;

alter table boards alter column id type bigint using id::bigint;
alter table menus alter column board_id type bigint using board_id::bigint;
alter table board_posts alter column board_id type bigint using board_id::bigint;

alter table boards alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('boards', 'id'), coalesce((select max(id) from boards), 1), (select count(*) > 0 from boards));

alter table menus
  add constraint menus_board_id_fkey
  foreign key (board_id) references boards(id) on delete set null;

commit;
