"use client";

import { useState } from "react";

export type QualityStatus = "Pass" | "Needs Review" | "Manual Required" | "Fail" | "Not Applicable";
export function QualitySection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="quality-section"><div className="quality-section-head"><h2>{title}</h2><span>Quality v1.0</span></div>{children}</section>; }
export function StatusBadge({ status }: { status: QualityStatus }) { return <span className={`quality-badge ${status.toLowerCase().replaceAll(" ", "-")}`}>{status}</span>; }
export function AuditTable({ rows }: { rows: Array<[string, string, string, QualityStatus]> }) { return <div className="quality-table">{rows.map(([item, rule, evidence, status]) => <div className="quality-row" key={item}><strong>{item}</strong><code>{rule}</code><span>{evidence}</span><StatusBadge status={status} /></div>)}</div>; }

const auditRows: Array<[string, string, string, QualityStatus]> = [["Text and status", "Perceivable", "State is not color-only", "Pass"], ["Keyboard actions", "Operable", "Primary controls use native elements", "Pass"], ["Clear recovery", "Understandable", "Errors include next action", "Pass"], ["Semantic structure", "Robust", "Landmarks and labels reviewed", "Needs Review"], ["Muted text contrast", "Color contrast", "Manual contrast review required", "Needs Review"], ["Dialog focus return", "Focus management", "Behavior specification documented", "Needs Review"], ["Reduced motion", "Motion", "Preference rule present", "Pass"]];
export function AccessibilityAudit() { return <div className="quality-stack"><QualitySection title="Perceivable · Operable · Understandable · Robust"><p className="quality-copy">This board records design-system guidance and review status. It is not an automated WCAG certification.</p><AuditTable rows={auditRows} /></QualitySection><QualitySection title="Before / After examples"><div className="quality-before-after"><div><strong>Before</strong><span>Color-only status · Placeholder-only input · Unnamed icon action</span></div><div><strong>After</strong><span>Icon + text + color · Explicit label · Accessible name and focus ring</span></div></div></QualitySection><QualitySection title="Keyboard and focus behavior"><div className="quality-keyboard-grid">{["Tab / Shift + Tab", "Enter / Space", "Escape", "Arrow keys", "Focus visible", "Focus return"].map((item) => <div key={item}><b>{item}</b><span>Expected behavior documented for review</span></div>)}</div></QualitySection></div>; }

const checklistGroups = { Component: ["Default, hover, focus, pressed", "Disabled, loading, and error", "Accessible name and keyboard", "320px and theme preview", "Reduced motion"], Pattern: ["Start, progress, and complete states", "Error recovery and cancel", "Keyboard flow and focus", "Mobile arrangement", "Danger action confirmation"], Template: ["Landmarks and current navigation", "Page title and primary action", "Loading, empty, and error", "Long text and max width", "Mobile sticky area"], "AI UX": ["Generating status and stop action", "Sources and confidence", "Human review required", "Correction and regeneration", "No false certainty"] };
export function Checklists() { const [states, setStates] = useState<Record<string, QualityStatus>>({}); const statuses: QualityStatus[] = ["Pass", "Needs Review", "Fail", "Not Applicable"]; return <div className="quality-stack">{Object.entries(checklistGroups).map(([group, items]) => <QualitySection title={`${group} checklist`} key={group}><div className="quality-checklist">{items.map((item) => { const key = `${group}-${item}`; const status = states[key] || "Needs Review"; return <div className="quality-check-item" key={item}><label><input type="checkbox" checked={status === "Pass"} onChange={() => setStates({ ...states, [key]: status === "Pass" ? "Needs Review" : "Pass" })} />{item}</label><select aria-label={`${item} status`} value={status} onChange={(e) => setStates({ ...states, [key]: e.target.value as QualityStatus })}>{statuses.map((option) => <option key={option}>{option}</option>)}</select></div>; })}</div></QualitySection>)}</div>; }

const gateSteps = ["Design Review", "Responsive Review", "Accessibility Review", "Code Quality Review", "Regression Review", "Documentation Review", "Release Decision"];
const productionCoreGates: Array<[string, string, string, QualityStatus]> = [["Gate 1", "TypeScript", "npx tsc --noEmit", "Pass"], ["Gate 2", "Design System ESLint", "components/design-system: 0 errors / 0 warnings", "Pass"], ["Gate 3", "Studio ESLint", "app/studio: 0 errors / 0 warnings", "Pass"], ["Gate 4", "Production Build", "Next.js production route generation", "Pass"], ["Gate 5", "Public API contract", "Typed entry point and internal helper boundary reviewed", "Pass"], ["Gate 6", "Accessibility contract", "Edge keyboard and accessibility-tree checks passed; screen-reader listening session remains environment-required", "Manual Required"], ["Gate 7", "320px and large text", "Edge 320px execution passed across all required Studio routes; 200% effective reflow passed", "Pass"], ["Gate 8", "Reduced Motion / Forced Colors", "Edge emulation matched both media queries; animation removal and visible control boundaries passed", "Pass"], ["Gate 9", "Regression", "75 static pages and required Studio routes generated", "Pass"]];
export function ReleaseGate() { const [current, setCurrent] = useState(2); return <div className="quality-stack"><QualitySection title="Release gate steps"><div className="quality-gate">{gateSteps.map((step, index) => <button key={step} className={index === current ? "active" : index < current ? "complete" : ""} onClick={() => setCurrent(index)}><b>{index < current ? "✓" : index + 1}</b><span>{step}</span></button>)}</div><div className="quality-gate-detail"><span className="quality-eyebrow">CURRENT REVIEW</span><h3>{gateSteps[current]}</h3><p>Evidence is reviewed manually for this stage. A release can be marked Ready only when the required checks are complete.</p></div></QualitySection><QualitySection title="Production Core v1.0 gate matrix"><AuditTable rows={productionCoreGates} /></QualitySection><QualitySection title="Manual verification procedure"><div className="quality-keyboard-grid"><div><b>Tabs</b><span>Focus Overview, run Right/Left/Home/End, confirm disabled Archive is skipped and the matching panel is labelled.</span></div><div><b>Modal lifecycle</b><span>Open Dialog, Drawer, and Sheet from each trigger; cycle Tab/Shift+Tab, press Escape, then confirm focus returns to that trigger.</span></div><div><b>Dismissal</b><span>Confirm the standard backdrop closes; confirm Protected confirmation ignores the backdrop while Close, Cancel, Delete, and Escape remain available.</span></div><div><b>Toast queue</b><span>Create four notifications, confirm only three display, focus does not move, action/dismiss work, and the fourth appears after dismissal or timeout.</span></div><div><b>320px / 200%</b><span>Review Form, Tabs, Feedback, and Overlay boards at 320px and 200% zoom for clipping, action collision, and page-level horizontal overflow.</span></div><div><b>User preferences</b><span>Emulate reduced motion and Windows forced colors; verify animations stop and control, focus, dialog, and toast boundaries remain visible.</span></div></div></QualitySection><QualitySection title="Repository ESLint policy"><div className="quality-evidence-list"><span>Production Core <StatusBadge status="Pass" /></span><span>Studio <StatusBadge status="Pass" /></span><span>Existing Application debt <StatusBadge status="Needs Review" /></span><span>Backup debt <StatusBadge status="Needs Review" /></span></div><p className="quality-copy">A Design System release requires Core and Studio to remain at zero errors and warnings. Unrelated application debt is reported and tracked separately; it is never hidden, added to ignore rules, or treated as resolved.</p></QualitySection><QualitySection title="Known issues and evidence"><div className="quality-known"><strong>Existing project lint debt</strong><span>47 errors / 31 warnings remain in legacy areas including sw_002, backups, and lib/sw007.ts.</span><small>New Design System and Studio changes must not increase this baseline.</small></div></QualitySection></div>; }
