"use client";

import { useState } from "react";

export type QualityStatus = "Pass" | "Needs Review" | "Fail" | "Not Applicable";
export function QualitySection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="quality-section"><div className="quality-section-head"><h2>{title}</h2><span>Quality v1.0</span></div>{children}</section>; }
export function StatusBadge({ status }: { status: QualityStatus }) { return <span className={`quality-badge ${status.toLowerCase().replaceAll(" ", "-")}`}>{status}</span>; }
export function AuditTable({ rows }: { rows: Array<[string, string, string, QualityStatus]> }) { return <div className="quality-table">{rows.map(([item, rule, evidence, status]) => <div className="quality-row" key={item}><strong>{item}</strong><code>{rule}</code><span>{evidence}</span><StatusBadge status={status} /></div>)}</div>; }

const auditRows: Array<[string, string, string, QualityStatus]> = [["Text and status", "Perceivable", "State is not color-only", "Pass"], ["Keyboard actions", "Operable", "Primary controls use native elements", "Pass"], ["Clear recovery", "Understandable", "Errors include next action", "Pass"], ["Semantic structure", "Robust", "Landmarks and labels reviewed", "Needs Review"], ["Muted text contrast", "Color contrast", "Manual contrast review required", "Needs Review"], ["Dialog focus return", "Focus management", "Behavior specification documented", "Needs Review"], ["Reduced motion", "Motion", "Preference rule present", "Pass"]];
export function AccessibilityAudit() { return <div className="quality-stack"><QualitySection title="Perceivable · Operable · Understandable · Robust"><p className="quality-copy">This board records design-system guidance and review status. It is not an automated WCAG certification.</p><AuditTable rows={auditRows} /></QualitySection><QualitySection title="Before / After examples"><div className="quality-before-after"><div><strong>Before</strong><span>Color-only status · Placeholder-only input · Unnamed icon action</span></div><div><strong>After</strong><span>Icon + text + color · Explicit label · Accessible name and focus ring</span></div></div></QualitySection><QualitySection title="Keyboard and focus behavior"><div className="quality-keyboard-grid">{["Tab / Shift + Tab", "Enter / Space", "Escape", "Arrow keys", "Focus visible", "Focus return"].map((item) => <div key={item}><b>{item}</b><span>Expected behavior documented for review</span></div>)}</div></QualitySection></div>; }

const checklistGroups = { Component: ["Default, hover, focus, pressed", "Disabled, loading, and error", "Accessible name and keyboard", "320px and theme preview", "Reduced motion"], Pattern: ["Start, progress, and complete states", "Error recovery and cancel", "Keyboard flow and focus", "Mobile arrangement", "Danger action confirmation"], Template: ["Landmarks and current navigation", "Page title and primary action", "Loading, empty, and error", "Long text and max width", "Mobile sticky area"], "AI UX": ["Generating status and stop action", "Sources and confidence", "Human review required", "Correction and regeneration", "No false certainty"] };
export function Checklists() { const [states, setStates] = useState<Record<string, QualityStatus>>({}); const statuses: QualityStatus[] = ["Pass", "Needs Review", "Fail", "Not Applicable"]; return <div className="quality-stack">{Object.entries(checklistGroups).map(([group, items]) => <QualitySection title={`${group} checklist`} key={group}><div className="quality-checklist">{items.map((item) => { const key = `${group}-${item}`; const status = states[key] || "Needs Review"; return <div className="quality-check-item" key={item}><label><input type="checkbox" checked={status === "Pass"} onChange={() => setStates({ ...states, [key]: status === "Pass" ? "Needs Review" : "Pass" })} />{item}</label><select aria-label={`${item} status`} value={status} onChange={(e) => setStates({ ...states, [key]: e.target.value as QualityStatus })}>{statuses.map((option) => <option key={option}>{option}</option>)}</select></div>; })}</div></QualitySection>)}</div>; }

const gateSteps = ["Design Review", "Responsive Review", "Accessibility Review", "Code Quality Review", "Regression Review", "Documentation Review", "Release Decision"];
export function ReleaseGate() { const [current, setCurrent] = useState(2); return <div className="quality-stack"><QualitySection title="Release gate steps"><div className="quality-gate">{gateSteps.map((step, index) => <button key={step} className={index === current ? "active" : index < current ? "complete" : ""} onClick={() => setCurrent(index)}><b>{index < current ? "✓" : index + 1}</b><span>{step}</span></button>)}</div><div className="quality-gate-detail"><span className="quality-eyebrow">CURRENT REVIEW</span><h3>{gateSteps[current]}</h3><p>Evidence is reviewed manually for this stage. A release can be marked Ready only when the required checks are complete.</p><div className="quality-evidence-list"><span>TypeScript <StatusBadge status="Pass" /></span><span>Stage lint <StatusBadge status="Pass" /></span><span>Full lint debt <StatusBadge status="Needs Review" /></span><span>320px review <StatusBadge status="Needs Review" /></span></div></div></QualitySection><QualitySection title="Known issues and evidence"><div className="quality-known"><strong>Existing project lint debt</strong><span>47 errors / 31 warnings remain in legacy areas including sw_002, backups, and lib/sw007.ts.</span><small>New Studio stages are tracked separately and must remain lint clean.</small></div></QualitySection></div>; }
