"use client";

import { useState } from "react";

export function AIPatternSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="ai-pattern-section"><div className="pattern-head"><h2>{title}</h2><span>AI Pattern v1.0</span></div>{children}</section>; }

export function PromptComposer() {
  const [prompt, setPrompt] = useState(""); const [sent, setSent] = useState(false);
  return <div className="ai-stack"><label className="ai-label" htmlFor="ai-prompt">What would you like to analyze?</label><textarea id="ai-prompt" value={prompt} onChange={(e) => { setPrompt(e.target.value); setSent(false); }} placeholder="Describe a task, question, or outcome..." rows={4} /><div className="ai-composer-foot"><span>{prompt.length}/500</span><div><button className="ai-quiet" onClick={() => setPrompt("")}>Clear</button><button className="ai-primary" disabled={!prompt.trim()} onClick={() => setSent(true)}>{sent ? "Submitted" : "Ask AI"}</button></div></div>{sent && <div className="ai-notice success">Prompt ready for processing. This is a local preview; no AI request was sent.</div>}<div className="ai-suggestions"><strong>Suggested prompts</strong><button onClick={() => setPrompt("Summarize the current project status")}>Summarize project status</button><button onClick={() => setPrompt("Find risks in this request")}>Find risks in this request</button><button onClick={() => setPrompt("Compare these two options")}>Compare two options</button></div><div className="ai-attachments"><strong>Attachments</strong><span>No files attached</span><button>+ Add file</button></div></div>;
}

export function ResponseCard() {
  const [streaming, setStreaming] = useState(true); const [copied, setCopied] = useState(false);
  return <div className="ai-stack"><div className="ai-response"><div className="ai-avatar" aria-hidden="true">AI</div><div className="ai-response-body"><div className="ai-response-meta"><strong>AI analysis</strong><span>{streaming ? "Generating" : "Complete"}</span></div><p>Project Atlas is progressing well. The latest request has three connected datasets and one item that needs review before completion.</p><div className="ai-response-section"><strong>Key findings</strong><ul><li>Data coverage is sufficient for the next step.</li><li>One validation item requires human review.</li></ul></div>{streaming && <div className="ai-progress"><i /></div>}<div className="ai-actions"><button onClick={() => setCopied(true)}>{copied ? "Copied" : "Copy"}</button><button onClick={() => setStreaming(!streaming)}>{streaming ? "Stop generation" : "Regenerate"}</button><button>Sources (2)</button></div></div></div><div className="ai-result-options"><strong>Compare suggestions</strong><button>Option A · concise</button><button>Option B · detailed</button></div></div>;
}

export function StatusTimeline() { const [status, setStatus] = useState("Analyzing request"); const statuses = ["Queued", "Analyzing request", "Checking sources", "Complete"]; return <div className="ai-stack"><div className="ai-status-controls">{statuses.map((item) => <button key={item} className={status === item ? "active" : ""} onClick={() => setStatus(item)}>{item}</button>)}</div><div className="ai-timeline">{statuses.map((item, index) => <div className={`ai-timeline-item ${statuses.indexOf(status) >= index ? "done" : ""}`} key={item}><b>{statuses.indexOf(status) >= index ? "✓" : index + 1}</b><div><strong>{item}</strong><span>{item === status ? "Current status" : index < statuses.indexOf(status) ? "Completed" : "Waiting"}</span></div></div>)}</div><div className="ai-tool-list"><div><span>Dataset check</span><b className="tool-done">Completed</b></div><div><span>Risk analysis</span><b className="tool-running">Running</b></div><div><span>Human review</span><b className="tool-waiting">Waiting</b></div></div><button className="ai-quiet">Retry if failed</button></div>; }

export function TrustPanel() { const [review, setReview] = useState(false); return <div className="ai-stack"><div className="ai-confidence"><div><strong>Confidence: Medium</strong><span>Based on available project data</span></div><div className="confidence-meter"><i /></div><small>Confidence describes supporting evidence, not guaranteed accuracy.</small></div><div className="ai-sources"><strong>Sources and limitations</strong><div><b>[1]</b><span>Project inventory · updated today</span><a href="#source">View source</a></div><div><b>[2]</b><span>Request history · 3 items</span><a href="#source">View source</a></div><p>Some information may be incomplete. Verify important decisions with the relevant owner.</p></div><div className="ai-review-banner"><strong>Human review required</strong><span>This suggestion could change project data. Review it before applying.</span><button className="ai-primary" onClick={() => setReview(!review)}>{review ? "Review acknowledged" : "Review suggestion"}</button></div><div className="ai-feedback"><strong>Was this response useful?</strong><button>Helpful</button><button>Needs correction</button><button>Report source issue</button></div></div>; }
