"use client";

import { useState } from "react";

const colors = [["--ndf-color-bg-page", "#07111f", "Semantic"], ["--ndf-color-bg-surface", "#112236", "Semantic"], ["--ndf-color-text-primary", "#f5f8fc", "Semantic"], ["--ndf-color-action-primary", "#4dd7c8", "Semantic"], ["--ndf-color-status-warning", "#f0b44b", "Semantic"], ["--ndf-blue-700", "#315dff", "Raw"]];
const spacing = [["--ndf-space-1", "4px"], ["--ndf-space-2", "8px"], ["--ndf-space-4", "16px"], ["--ndf-space-6", "24px"], ["--ndf-space-8", "32px"], ["--ndf-space-12", "48px"]];

export function FoundationSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="foundation-token-section"><div className="foundation-token-head"><h2>{title}</h2><span>Foundation v1.0</span></div>{children}</section>; }
export function TokenBoard() { return <div className="foundation-token-stack"><FoundationSection title="Token architecture"><p className="foundation-token-copy">Raw values establish the palette and scale. Semantic tokens describe intent. Component tokens are reserved for repeated component decisions that semantic tokens cannot express.</p><div className="foundation-layers"><div><b>01 Raw</b><span>Blue, neutral, space, radius</span></div><div><b>02 Semantic</b><span>Page, surface, text, action, status</span></div><div><b>03 Component</b><span>Button, card, input, navigation</span></div></div></FoundationSection><FoundationSection title="Color tokens"><div className="foundation-color-grid">{colors.map(([name, value, type]) => <div className="foundation-color-token" key={name}><i style={{ background: value }} /><code>{name}</code><strong>{value}</strong><small>{type} · preview usage</small></div>)}</div></FoundationSection><FoundationSection title="Typography, spacing, radius, and shadow"><div className="foundation-type-sample"><span>Page title · 32 / 1.15</span><strong>Clear hierarchy for focused work</strong><p>Body text uses the existing sans family and readable line height.</p></div><div className="foundation-spacing-grid">{spacing.map(([name, value]) => <div key={name}><code>{name}</code><i style={{ width: value }} /><small>{value}</small></div>)}</div><div className="foundation-radius-grid"><div className="radius-sm">Small</div><div className="radius-md">Medium</div><div className="radius-lg">Large</div><div className="shadow-md">Shadow</div></div></FoundationSection><FoundationSection title="Motion and z-index"><div className="foundation-token-list"><div><code>--ndf-motion-duration-fast</code><span>120ms · small control feedback</span></div><div><code>--ndf-motion-duration-normal</code><span>200ms · enter and exit</span></div><div><code>--ndf-z-header</code><span>30 · named layer order</span></div><div><code>--ndf-z-dialog</code><span>60 · named overlay order</span></div></div></FoundationSection></div>; }

export function ThemeBoard() { const [theme, setTheme] = useState("light"); return <div className="foundation-theme-wrap"><div className="foundation-theme-toolbar" role="group" aria-label="Theme preview"><span>Preview theme</span>{["light", "dark", "high-contrast"].map((item) => <button key={item} className={theme === item ? "active" : ""} onClick={() => setTheme(item)}>{item}</button>)}</div><div className={`foundation-theme-preview ${theme}`} data-ndf-theme={theme}><div className="theme-preview-header"><strong>NexDataForge</strong><span>Theme preview · local only</span></div><div className="theme-preview-grid"><aside><b>Workspace</b><span className="selected">Overview</span><span>Projects</span><span>Requests</span></aside><main><span className="theme-kicker">SAMPLE DATA</span><h2>Project overview</h2><p>Semantic tokens change the preview surface while page structure stays stable.</p><div className="theme-cards"><div><small>All projects</small><strong>24</strong></div><div><small>Needs review</small><strong>03</strong></div></div><button className="theme-action">Primary action</button></main></div></div><div className="foundation-theme-notes"><div><strong>Light</strong><span>Default Studio foundation</span></div><div><strong>Dark</strong><span>Preview only, no global application</span></div><div><strong>High contrast</strong><span>Review contrast and focus visibility</span></div></div></div>; }
